
# PATH = $(shell pwd)
# MYPATH = $(shell ls *.c)

# DE:MY ABC
# 	$(info 789)

# MY:
# 	$(info 000)	
# 	$(info $(MYPATH))
# 	$(info 123)



# ABC:
# 	$(info 456)

# MYPATH = $(shell pwd)


# MYPATH = $(shell ls *.c)
MYC = week.c
OBJ = week.o
CC = gcc
OUTPUT_DIR = bin
Debug:
	$(CC) -c $(MYC) -o $(OUTPUT_DIR)/$(OBJ)
	@echo $(CC)

clean:
	# rm $(OUTPUT_DIR)/*.o 